apiVersion: v1
kind: Pod
metadata:
  name: kuard-amd64-blue-makanga-pothieux-memory
spec:
  containers:
  - image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/kuard:blue
    name: kuard-amd64-blue-makanga-pothieux-memory
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
      limits:
        cpu: "50m"
        memory: "128Mi"
