apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: frontend
    soft: nginx
  name: kuard-amd64-blue-makanga-pothieux-replicaset
spec:
  replicas: 1                     
  selector:
    matchLabels:
      app: frontend
      soft: nginx
  template:                   
    metadata:
      labels:
        app: frontend
        soft: nginx
    spec:
      containers:
      - image: europe-west1-docker.pkg.dev/polytech-dijon/polytech-dijon/kuard:blue
        name: kuard-amd64-blue-makanga-pothieux-replicaset
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
